server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always

base:
  path: /api/v1

logging:
  level:
    org.springframework.security: TRACE

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/lms
    username: root
    password: P@ssw0rd
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect

